[package]
name = "json_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde_qs = { version = "0.15", features = ["actix-web4"] }
serde = { version = "1", features = ["derive"] }
resources = { path = "resources" }
serde_json = "1.0.140"
