/*
 * json_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountList200ResponseAllOfDataInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "attributes")]
    pub attributes: Box<models::GetAccountList200ResponseAllOfDataInnerAllOfAttributes>,
}

impl GetAccountList200ResponseAllOfDataInner {
    pub fn new(id: String, r#type: Type, attributes: models::GetAccountList200ResponseAllOfDataInnerAllOfAttributes) -> GetAccountList200ResponseAllOfDataInner {
        GetAccountList200ResponseAllOfDataInner {
            id,
            r#type,
            attributes: Box::new(attributes),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "account")]
    Account,
}

impl Default for Type {
    fn default() -> Type {
        Self::Account
    }
}

