/*
 * json_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccount200Response {
    #[serde(rename = "data")]
    pub data: Box<models::GetAccountList200ResponseAllOfDataInner>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
}

impl GetAccount200Response {
    pub fn new(data: models::GetAccountList200ResponseAllOfDataInner) -> GetAccount200Response {
        GetAccount200Response {
            data: Box::new(data),
            meta: None,
        }
    }
}

