/*
 * json_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountList200Response {
    #[serde(rename = "data")]
    pub data: Vec<models::GetAccountList200ResponseAllOfDataInner>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
}

impl GetAccountList200Response {
    pub fn new(data: Vec<models::GetAccountList200ResponseAllOfDataInner>) -> GetAccountList200Response {
        GetAccountList200Response {
            data,
            meta: None,
            links: None,
        }
    }
}

