/*
 * json_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountList200ResponseAllOfDataInnerAllOfAttributes {
    /// Tron address
    #[serde(rename = "address")]
    pub address: String,
}

impl GetAccountList200ResponseAllOfDataInnerAllOfAttributes {
    pub fn new(address: String) -> GetAccountList200ResponseAllOfDataInnerAllOfAttributes {
        GetAccountList200ResponseAllOfDataInnerAllOfAttributes {
            address,
        }
    }
}

